# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created

name: Java Maven CI

# Used for automatically triggering a workflow given an event
on:
# Specifying the event, can be multiple such as [push, fork]
  push:
    branches: dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # can provide names to steps for clarity
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11' # java 11 used for this example 
        distribution: 'temurin' # vendor used for this example

    - name: Build with Maven
    # pom.xml file should be generated when creating the project in intellij
      run: mvn -B package --file pom.xml
      
    - name: List current directory
      run: ls -a
    
    # Target folder should be generated when running maven
    - name: List target folder contents
      run: |
        cd target
        ls -a
